LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := icu53.c
LOCAL_SHARED_LIBRARIES := libicuuc libicui18n
LOCAL_MULTILIB := both
#LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_PATH_32 := ${TARGET_OUT}/lib
LOCAL_MODULE_PATH_64 := $(TARGET_OUT)/lib64
#LOCAL_MODULE_RELATIVE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE := libshim_icu53
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)
